version: "3"
services:
  nginx:
    image: nginx
    container_name: website-nginx
    volumes:
      - /www/website/nginx.conf:/etc/nginx/nginx.conf
      - /www/website/public:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=static.thy.pub
      - NGINX_PORT=80
    networks:
      - website
  redis:
    image: redis
    container_name: website-redis
    volumes:
      - redis-volume:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - website
  api:
    image: openjdk:8
    container_name: website-api
    volumes: 
      - /www/website:/app
      - /www/data:/data
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: unless-stopped
    logging:
      options:
        max-size: "100m"
    working_dir: /app
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_PWD=${MYSQL_PWD}
      - MYSQL_HOST=${MYSQL_HOST}
    networks:
      - website
    command: java -jar "-Dspring.profiles.active=prod,druid" website-admin.jar

volumes:
  redis-volume:

networks:
  website:
    name: website