# 项目相关配置
ruoyi:
  demoEnabled: false
  profile: /data/upload

# 日志配置
logging:
  level:
    com.ruoyi: error
    org.springframework: error

token:
  # 令牌有效期（默认30分钟）
  expireTime: 60

# Spring配置
spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: false

# 本网站配置
website:
  dataRoot: /data